/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentTreeNode: typeof import('./components/ComponentTreeNode.vue')['default']
    DockingPanel: typeof import('./components/DockingPanel.vue')['default']
    IframeView: typeof import('./components/IframeView.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RoutePathItem: typeof import('./components/RoutePathItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesTable: typeof import('./components/RoutesTable.vue')['default']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SideNav: typeof import('./components/SideNav.vue')['default']
    SideNavItem: typeof import('./components/SideNavItem.vue')['default']
    StateFields: typeof import('./components/StateFields.vue')['default']
    StateFieldsTree: typeof import('./components/StateFieldsTree.vue')['default']
    TabIcon: typeof import('./components/TabIcon.vue')['default']
    TimelineEvent: typeof import('./components/TimelineEvent.vue')['default']
    VBadge: typeof import('./ui-kit/VBadge.vue')['default']
    VButton: typeof import('./ui-kit/VButton.vue')['default']
    VDarkToggle: typeof import('./ui-kit/VDarkToggle.vue')['default']
    VExpandIcon: typeof import('./ui-kit/VExpandIcon.vue')['default']
    VIcon: typeof import('./ui-kit/VIcon.vue')['default']
    VIconTitle: typeof import('./ui-kit/VIconTitle.vue')['default']
    VPanelGrids: typeof import('./ui-kit/VPanelGrids.vue')['default']
    VSectionBlock: typeof import('./ui-kit/VSectionBlock.vue')['default']
    VTextInput: typeof import('./ui-kit/VTextInput.vue')['default']
  }
}
