/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentState: typeof import('./components/ComponentState.vue')['default']
    ComponentStateField: typeof import('./components/ComponentStateField.vue')['default']
    ComponentTreeNode: typeof import('./components/ComponentTreeNode.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    SideNav: typeof import('./components/SideNav.vue')['default']
    SideNavItem: typeof import('./components/SideNavItem.vue')['default']
    TabIcon: typeof import('./components/TabIcon.vue')['default']
    TimelineEvent: typeof import('./components/TimelineEvent.vue')['default']
    TimelineEventInfo: typeof import('./components/TimelineEventInfo.vue')['default']
    VButton: typeof import('./components/VButton.vue')['default']
  }
}
